services:
  server:
    container_name: crm-backend
    image: ${DOCKER_USERNAME}/crm-server:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - crm-network

  client:
    container_name: crm-frontend
    image: ${DOCKER_USERNAME}/crm-client:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
